### ISSUE TITLE
Disable directly pushing to master after tagging v0.1

### ISSUE THREAD

**Issue by andidavies92** [Stack-in-a-box/triumphmayflowerclub.com#6]
# Overview

Once the website has a first-draft of all content, we should mark master as a protected branch and only ever do work on separate branches. This will insure we (hopefully) never need to modify master's Git history after this point as all WIP commits will be on their own branches and will only get merged via PRs once they're finished. This should also mean that the site that's hosted on GitHub Pages is always kept in a working state and doesn't contain any half-finished implementations.

# Dependencies

* #4 – _Write repository readme_
* #5 – _Complete first-draft of all website content_

# Tasks

- [ ] Establish and document a branch naming convention.
- [ ] Mark `master` as a protected branch.
- [x] Tag and release v1.0.
